baseURL = 'https://danielmelar.com/'
languageCode = 'pt-br'
title = 'Daniel Melo Aguilar'
theme = 'archie'

paginate = 2

[params]
mode = 'auto'
mainSections = ["posts", "projects"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/danielmelar"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/danielmelar/"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/danielmeloaguilar"

[[menu.main]]
name = "Início"
url = "/"
weight = 1

[[menu.main]]
name = "Publicações"
url = "/posts"
weight = 2

[[menu.main]]
name = "Notas"
url = "/posts/notes"
weight = 3

[[menu.main]]
name = "Projetos"
url = "/projects"
weight = 4

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

